/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install and kept here so type
// checking has the expected ambient declarations from the first run.
